parameters:
#    o_auth.example.class: CDE\OAuthBundle\Example

services:
  cde_oauth.manager.client:
    class: CDE\OAuthBundle\Entity\ClientManager
    arguments:
      em: '@Doctrine.orm.entity_manager'
      class: CDE\OAuthBundle\Entity\Client
      codeClass: CDE\OAuthBundle\Entity\AuthCode
      accessClass: CDE\OAuthBundle\Entity\AccessToken
      refreshClass: CDE\OAuthBundle\Entity\RefreshToken
      clientManager: '@fos_oauth_server.client_manager.default'
      paginator: '@knp_paginator'
