cde_stripe:
    resource: "@CDEStripeBundle/Resources/config/routing.yml"
    prefix:   /

o_auth:
    resource: "@CDEOAuthBundle/Resources/config/routing.yml"
    prefix:   /

cde_test:
    resource: "@CDETestBundle/Resources/config/routing.yml"
    prefix:   /

CDECartBundle:
    resource: "@CDECartBundle/Resources/config/routing.yml"
    prefix:   /

CDECartBundleAPI:
    resource: "@CDECartBundle/Resources/config/routingAPI.yml"
    prefix:   /api

CDEContentBundle:
    resource: "@CDEContentBundle/Resources/config/routing.yml"
    prefix:   /admin/content

CDEContentBundleAPI:
    resource: "@CDEContentBundle/Resources/config/routingAPI.yml"
    prefix:   /api

CDESubscriptionBundle:
    resource: "@CDESubscriptionBundle/Resources/config/routing.yml"
    prefix:   /admin/subscription

CDEUserBundle:
    resource: "@CDEUserBundle/Resources/config/routing.yml"
    prefix:   /user

CDEAdminBundle:
    resource: "@CDEAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

CDEUtilityBundle:
    resource: "@CDEUtilityBundle/Resources/config/routing.yml"
    prefix:   /

CDEAffiliateBundle:
    resource: "@CDEAffiliateBundle/Resources/config/routing.yml"
    prefix:   /

CDEAngular:
    resource: "@CDEUtilityBundle/Resources/config/angular-routing.yml"
    prefix:   /angular


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

# FOS User Bundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# FOS JS Routing Bundle
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# FOS OAuth Server Bundle
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
