security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      in_memory:
          memory:
            users:
              user:  { password: userpass, roles: [ 'ROLE_USER' ] }
              admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
      fos_userbundle:
        id: fos_user.user_provider.username

    firewalls:
      api:
        pattern: ^/api
        fos_oauth: true
        stateless: true
#      oauth_authorize:
#          pattern: ^/oauth/v2/auth
#          form_login:
#              provider: fos_userbundle
#              check_path: /oauth/v2/auth_login_check
#              login_path: /oauth/v2/auth_login
#          anonymous: true
#l
      main:
        pattern: ^/
        form_login:
          provider: fos_userbundle
          csrf_provider: form.csrf_provider
        logout: 
          invalidate_session: false
        anonymous:  true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/user/admin, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/api, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/class, role: ROLE_USER }
        - { path: ^/user, role: ROLE_USER }
        - { path: ^/gallery, role: ROLE_USER }
        - { path: ^/comment, role: ROLE_USER }

    encoders:
            FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN
