parameters:
#    cde_admin.example.class: CDE\AdminBundle\Example

services:
#    cde_admin.example:
#        class: %cde_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
