discounts:
    pattern: /discount/{id}
    defaults: { _controller: CDECartBundle:Rest:discount, id: null }
    methods: [GET]

discounts_create:
    pattern: /discount
    defaults: { _controller: CDECartBundle:Rest:discountCreate}
    methods: [POST]

discounts_update:
    pattern: /discount/{id}
    defaults: { _controller: CDECartBundle:Rest:discountUpdate}
    methods: [PUT, POST]
    requirements:
          id: \d+

discounts_delete:
    pattern: /discount/{id}
    defaults: { _controller: CDECartBundle:Rest:discountDelete}
    methods: [DELETE]
    requirements:
      id: \d+

discounts_delete_test:
    pattern: /discount/{id}/delete
    defaults: { _controller: CDECartBundle:Rest:discountDelete}
    methods: [GET]
    requirements:
      id: \d+

transactions:
    pattern: /transactions/{page}/{limit}
    defaults: { _controller: CDECartBundle:Rest:transactions, page: 1, limit: 10 }
    methods: [GET]

transaction:
    pattern: /transaction/{id}
    defaults: { _controller: CDECartBundle:Rest:transaction }
    methods: [GET]
    requirements:
      id: \d+

transactions_update:
    pattern: /transaction/{id}
    defaults: { _controller: CDECartBundle:Rest:transactionUpdate}
    methods: [PUT, POST]
    requirements:
          id: \d+