CDE\CartBundle\Entity\Cart:
  properties:
    id: 
      - NotBlank: { groups: [csrf_only] }

CDE\CartBundle\Entity\Discount:
  properties:
    id: 
      - NotBlank: { groups: [csrf_only] }
    expires:
      - NotBlank: ~
#    uses:
#      - Range:
#      min: 0
#    maxUses:
#      - Range:
#      min: 0
#      max: 100000
#    value:
#      - Range:
#      min: 0
#      max: 100000
#    percent:
#      - Range:
#      min: 0
#      max: 100
CDE\CartBundle\Entity\Product:
  properties:
    id: 
      - NotBlank: { groups: [csrf_only] }
      
CDE\CartBundle\Entity\Transaction:
  properties:
    id: 
      - NotBlank: { groups: [csrf_only] }