parameters:
  security.authentication.success_handler.class: CDE\UserBundle\Handler\LoginSuccessHandler
  security.authentication.failure_handler.class: CDE\UserBundle\Handler\LoginFailureHandler
#    cde_user.example.class: CDE\UserBundle\Example

services:
  fos_user.user_provider:
    class: FOS\UserBundle\Security\UserProvider
    arguments:
      userManager: '@fos_user.user_manager'
  cde_user.registration.form.type:
    class: CDE\UserBundle\Form\Type\RegistrationFormType
    arguments: [%fos_user.model.user.class%]
    tags:
      - { name: form.type, alias: cde_user_registration }
  cde_user.manager.user:
    class: CDE\UserBundle\Entity\UserManager
    arguments:
      em: '@doctrine.orm.entity_manager'
      class: CDE\UserBundle\Entity\User
      userManager: '@fos_user.user_manager'
      userProvider: '@fos_user.user_provider'
      subscriptionManager: '@cde_subscription.manager.subscription'
      affiliateManager: '@cde_affiliate.manager.affiliate'
      paginator: '@knp_paginator'
      encoderFactory: '@security.encoder_factory'
      validator: '@validator'
  cde_user.manager.address:
    class: CDE\UserBundle\Entity\AddressManager
    arguments:
      em: '@doctrine.orm.entity_manager'
      class: CDE\UserBundle\Entity\Address
      paginator: '@knp_paginator'
  security.authentication.customized_success_handler:
          class: %security.authentication.success_handler.class%
          public: false
          arguments:  [@router, @security.context]
  security.authentication.customized_failure_handler:
            class: %security.authentication.failure_handler.class%
            public: false
            arguments:  [@router, @security.context]