# Comments
CDEContentBundle_api_create_comment:
    pattern: gallery/{id}/comment
    defaults: { _controller: CDEContentBundle:Rest:createComment }
    methods: [POST]
    requirements:
      id: \d+

CDEContentBundle_api_get_comment:
    pattern: comment/{id}
    defaults: { _controller: CDEContentBundle:Rest:getComment }
    methods: [GET]
    requirements:
      id: \d+

CDEContentBundle_api_update_comment:
    pattern: comment/{id}
    defaults: { _controller: CDEContentBundle:Rest:updateComment }
    methods: [PUT, POST]
    requirements:
      id: \d+

CDEContentBundle_api_delete_comment:
    pattern: comment/{id}
    defaults: { _controller: CDEContentBundle:Rest:deleteComment }
    methods: [DELETE]
    requirements:
      id: \d+

CDEContentBundle_api_delete_comment_GET:
    pattern: comment/{id}/delete
    defaults: { _controller: CDEContentBundle:Rest:deleteComment }
    methods: [GET]
    requirements:
      id: \d+

CDEContentBundle_api_get_comments:
    pattern: page/{page}/limit/{limit}/comment
    defaults: { _controller: CDEContentBundle:Rest:getComments, page: 1, limit: 10 }

# Galleries
CDEContentBundle_api_get_galleries:
    pattern: page/{page}/limit/{limit}/gallery
    defaults: { _controller: CDEContentBundle:Rest:getGalleries, page: 1, limit: 10 }

CDEContentBundle_api_get_gallery:
    pattern: gallery/{id}
    defaults: { _controller: CDEContentBundle:Rest:getGallery }
    methods: [GET]

CDEContentBundle_api_update_gallery:
    pattern: gallery/{id}
    defaults: { _controller: CDEContentBundle:Rest:updateGallery }
    methods: [PUT, POST]
    requirements:
      id: \d+