# Comments
CDEContentBundle_api_create_comment:
    pattern: createComment/{id}
    defaults: { _controller: CDEContentBundle:Rest:createComment }
    methods: [POST]
    requirements:
      id: \d+

CDEContentBundle_api_get_comment:
    pattern: getComment/{id}
    defaults: { _controller: CDEContentBundle:Rest:getComment }
    requirements:
      id: \d+

CDEContentBundle_api_update_comment:
    pattern: updateComment/{id}
    defaults: { _controller: CDEContentBundle:Rest:updateComment }
    methods: [PUT, POST]
    requirements:
      id: \d+

CDEContentBundle_api_delete_comment:
    pattern: deleteComment/{id}
    defaults: { _controller: CDEContentBundle:Rest:deleteComment }
    methods: [GET, DELETE]
    requirements:
      id: \d+

CDEContentBundle_api_get_comments:
    pattern: getComments/{page}/{limit}
    defaults: { _controller: CDEContentBundle:Rest:getComments, page: 1, limit: 10 }

# Galleries
CDEContentBundle_api_get_gallieries:
    pattern: getGalleries/{page}/{limit}
    defaults: { _controller: CDEContentBundle:Rest:getGalleries, page: 1, limit: 10 }