#Angular Params
CDEUtilityBundle_angular_params:
    pattern: /params
    defaults: { _controller: CDEUtilityBundle:Angular:params }
    methods: [GET]
    options:
      expose: true

#Angular Utility
CDEUtilityBundle_angular_login:
    pattern: /login.html
    defaults: { _controller: CDEUtilityBundle:Angular:login }
    options:
      expose: true

CDEUtilityBundle_angular_register:
    pattern: /register.html
    defaults: { _controller: CDEUtilityBundle:Angular:register }
    options:
      expose: true

CDEUtilityBundle_angular_reset:
    pattern: /reset.html
    defaults: { _controller: CDEUtilityBundle:Angular:reset }
    options:
      expose: true

CDEUtilityBundle_angular_reset_email:
    pattern: /reset
    defaults: { _controller: CDEUserBundle:Resetting:customEmail }
    methods: [POST]
    options:
      expose: true

CDEUtilityBundle_angular_resetting_form:
    pattern: /resetting.html/{token}
    defaults: { _controller: CDEUserBundle:Resetting:reset, token: null }
    methods: [GET]
    options:
      expose: true

CDEUtilityBundle_angular_resetting:
    pattern: /resetting/{token}
    defaults: { _controller: CDEUserBundle:Resetting:reset }
    methods: [POST, GET]
    options:
      expose: true

CDEUtilityBundle_angular_image_list:
    pattern: /images/{prefix}
    defaults: { _controller: CDEUtilityBundle:Angular:listImages }
    options:
      expose: true

#User Actions
CDEUtilityBundle_angular_user:
    pattern: /user
    defaults: { _controller: CDEUtilityBundle:Angular:user }
    methods: [GET]
    options:
      expose: true

CDEUtilityBundle_angular_user_update:
    pattern: /user
    defaults: { _controller: CDEUtilityBundle:Angular:userUpdate }
    methods: [POST]
    options:
      expose: true

#Address Actions
CDEUtilityBundle_angular_address:
    pattern: /address
    defaults: { _controller: CDEUtilityBundle:Angular:address }
    methods: [GET]
    options:
      expose: true

CDEUtilityBundle_angular_address_update:
    pattern: /address
    defaults: { _controller: CDEUtilityBundle:Angular:addressUpdate }
    methods: [POST]
    options:
      expose: true

#Transaction Actions
CDEUtilityBundle_angular_transaction:
    pattern: /transaction/{id}
    defaults: { _controller: CDEUtilityBundle:Angular:transaction, id: null }
    methods: [GET]
    options:
      expose: true

#Product Actions
CDEUtilityBundle_angular_product:
    pattern: /product/{id}
    defaults: { _controller: CDEUtilityBundle:Angular:product, id: null }
    methods: [GET]
    options:
      expose: true

#Cart Actions
CDEUtilityBundle_angular_cart:
    pattern: /cart
    defaults: { _controller: CDEUtilityBundle:Angular:cart }
    methods: [GET]
    options:
      expose: true

CDEUtilityBundle_angular_cart_add:
    pattern: /cart
    defaults: { _controller: CDEUtilityBundle:Angular:addToCart }
    methods: [POST]
    options:
      expose: true

CDEUtilityBundle_angular_cart_remove:
    pattern: /cart/update
    defaults: { _controller: CDEUtilityBundle:Angular:updateCart }
    methods: [POST]
    options:
      expose: true

CDEUtilityBundle_angular_cart_discount:
    pattern: /discount
    defaults: { _controller: CDEUtilityBundle:Angular:discount }
    methods: [POST]
    options:
      expose: true

CDEUtilityBundle_angular_token:
    pattern: /token
    defaults: { _controller: CDEUtilityBundle:Angular:token }
    methods: [GET]
    options:
      expose: true

CDEUtilityBundle_angular_token_create:
    pattern: /token
    defaults: { _controller: CDEUtilityBundle:Angular:tokenCreate }
    methods: [POST]
    options:
      expose: true

CDEUtilityBundle_angular_stripe_checkout:
    pattern: /stripe/checkout
    defaults: { _controller: CDEUtilityBundle:Angular:stripeCheckout }
    methods: [GET]
    options:
      expose: true

#Subscription routes
CDEUtilityBundle_angular_subscription:
    pattern: /subscription/{id}
    defaults: { _controller: CDEUtilityBundle:Angular:subscription, id: null }
    methods: [GET]
    options:
      expose: true

CDEUtilityBundle_angular_subscription_reset:
    pattern: /subscription/{id}/reset
    defaults: { _controller: CDEUtilityBundle:Angular:subscriptionReset }
    methods: [GET]
    options:
      expose: true

#Content routes
CDEUtilityBundle_angular_content:
    pattern: /content/{slug}
    defaults: { _controller: CDEUtilityBundle:Angular:content }
    methods: [GET]
    options:
      expose: true

#Page routes
CDEUtilityBundle_angular_page:
    pattern: /page/{slug}
    defaults: { _controller: CDEUtilityBundle:Angular:page }
    methods: [GET]
    options:
      expose: true

#Gallery routes
CDEUtilityBundle_angular_gallery:
    pattern: /gallery/{id}
    defaults: { _controller: CDEUtilityBundle:Angular:gallery, id: null }
    methods: [GET]
    options:
      expose: true

CDEUtilityBundle_angular_gallery_create:
    pattern: /gallery
    defaults: { _controller: CDEUtilityBundle:Angular:galleryCreate, id: null }
    methods: [POST]
    options:
      expose: true

CDEUtilityBundle_angular_gallery_delete:
    pattern: /gallery/{id}
    defaults: { _controller: CDEUtilityBundle:Angular:galleryDelete}
    methods: [DELETE]
    options:
      expose: true

#Comment routes
CDEUtilityBundle_angular_comment:
    pattern: /comment/{id}
    defaults: { _controller: CDEUtilityBundle:Angular:comment, id: null }
    methods: [GET]
    options:
      expose: true

CDEUtilityBundle_angular_comment_create:
    pattern: /gallery/{id}/comment
    defaults: { _controller: CDEUtilityBundle:Angular:commentCreate }
    methods: [POST]
    options:
      expose: true